server:
  port: 8004
spring:
  application:
    name: service-cms
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/guli?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&usessl=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
  jackson:
    #时区，默认为格林尼治时间，即少8小时，所以我们需要+8
    time-zone: GMT+8
    #时间格式转换定义
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
    database: 0
    # 默认情况下spring-data-redis使用lettuce，你可以替换为jedis
    lettuce:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 5
        max-wait: 1ms
      shutdown-timeout: 1000ms
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl