server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: TFRBSTRHMkNpVHBrcTZBQnc0Y0QxYm8z
  accessKeySecret: em4yanBpNVlYb1pXRm5Vem1QZk5kcTFiT0doQ2tC
  bucketName: guli-twy