server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4GEoEjeiGAYq1KvDQaQB
  accessKeySecret: UttBTDfn2Rl8j0Teq9XRHI6zE54yls
  bucketName: guli-twy