server:
  port: 8002
spring:
  application:
    name: service_oss
  profiles:
    active: dev
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIN6I0pGXdSMro123
  accessKeySecret: 1ifq9fHJ8spvsRaY9x9gI4zC0pROcY123
  bucketName: guli-twy