server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: TFRBSTRHRW9FamVpR0FZcTFLdkRRYVFC
  accessKeySecret: VXR0QlREZm4yUmw4ajBUZXE5WFJISTZ6RTU0eWxz
  bucketName: guli-twy