server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GEoEjeiGAYq1KvDQaQB123
  accessKeySecret: UttBTDfn2Rl8j0Teq9XRHI6zE54yls123
  bucketName: guli-twy